name: All Smiles Dentistry Allen
favicon: null
layout_spectrum: 0.8836472798138857
typography_spectrum: 0.013813205296173692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.223060536198318
  lightness: 0.6490158759988844
  saturation: 0.568784661591053
  rhythmicContrast: 0.12620584573596716
purpose: []
